#include <Buma3D/Buma3D.h>
#include "./FormatUtils.h"

namespace buma3d
{
namespace util
{

size_t GetFormatSize(RESOURCE_FORMAT _format)
{
    // NOTE: 返されるサイズはそのフォーマットで割当可能な解像度の最小値を適用した際のサイズです。
    // フォーマットサイズが2でブロックサイズが2x2の場合8が返ります。

    switch (_format)
    {
    case RESOURCE_FORMAT_R8_TYPELESS:
    case RESOURCE_FORMAT_R8_UNORM:
    case RESOURCE_FORMAT_R8_SNORM:
    case RESOURCE_FORMAT_R8_UINT:
    case RESOURCE_FORMAT_R8_SINT:
        return 1;

    case RESOURCE_FORMAT_R16_TYPELESS:
    case RESOURCE_FORMAT_R16_UNORM:
    case RESOURCE_FORMAT_R16_SNORM:
    case RESOURCE_FORMAT_R16_UINT:
    case RESOURCE_FORMAT_R16_SINT:
    case RESOURCE_FORMAT_R16_FLOAT:
    case RESOURCE_FORMAT_R8G8_TYPELESS:
    case RESOURCE_FORMAT_R8G8_UNORM:
    case RESOURCE_FORMAT_R8G8_SNORM:
    case RESOURCE_FORMAT_R8G8_UINT:
    case RESOURCE_FORMAT_R8G8_SINT:
    case RESOURCE_FORMAT_B5G6R5_UNORM:
    case RESOURCE_FORMAT_B5G5R5A1_UNORM:
    case RESOURCE_FORMAT_D16_UNORM:
        return 2;

    case RESOURCE_FORMAT_Y8_U8V8_2PLANE_420_UNORM:
        return 3;

    case RESOURCE_FORMAT_R32_TYPELESS:
    case RESOURCE_FORMAT_R32_UINT:
    case RESOURCE_FORMAT_R32_SINT:
    case RESOURCE_FORMAT_R32_FLOAT:
    case RESOURCE_FORMAT_R16G16_TYPELESS:
    case RESOURCE_FORMAT_R16G16_UNORM:
    case RESOURCE_FORMAT_R16G16_SNORM:
    case RESOURCE_FORMAT_R16G16_UINT:
    case RESOURCE_FORMAT_R16G16_SINT:
    case RESOURCE_FORMAT_R16G16_FLOAT:
    case RESOURCE_FORMAT_R11G11B10_UFLOAT:
    case RESOURCE_FORMAT_R8G8B8A8_TYPELESS:
    case RESOURCE_FORMAT_R8G8B8A8_UNORM:
    case RESOURCE_FORMAT_R8G8B8A8_UNORM_SRGB:
    case RESOURCE_FORMAT_R8G8B8A8_SNORM:
    case RESOURCE_FORMAT_R8G8B8A8_UINT:
    case RESOURCE_FORMAT_R8G8B8A8_SINT:
    case RESOURCE_FORMAT_R10G10B10A2_TYPELESS:
    case RESOURCE_FORMAT_R10G10B10A2_UNORM:
    case RESOURCE_FORMAT_R10G10B10A2_UINT:
    case RESOURCE_FORMAT_R9G9B9E5_UFLOAT:
    case RESOURCE_FORMAT_D32_FLOAT:
    case RESOURCE_FORMAT_D24_UNORM_S8_UINT:
    case RESOURCE_FORMAT_D32_FLOAT_S8X24_UINT:
    case RESOURCE_FORMAT_Y8U8Y8V8_422_UNORM:
    case RESOURCE_FORMAT_X6Y10_X6U10X6V10_2PLANE_420_UNORM_PLANE1:
    case RESOURCE_FORMAT_Y16_U16V16_2PLANE_420_UNORM_PLANE1:
        return 4;

    case RESOURCE_FORMAT_X6Y10_X6U10X6V10_2PLANE_420_UNORM:
    case RESOURCE_FORMAT_Y16_U16V16_2PLANE_420_UNORM:
        return 6;

    case RESOURCE_FORMAT_R32G32_TYPELESS:
    case RESOURCE_FORMAT_R32G32_SINT:
    case RESOURCE_FORMAT_R32G32_FLOAT:
    case RESOURCE_FORMAT_R16G16B16A16_TYPELESS:
    case RESOURCE_FORMAT_R16G16B16A16_SNORM:
    case RESOURCE_FORMAT_R16G16B16A16_UINT:
    case RESOURCE_FORMAT_R16G16B16A16_SINT:
    case RESOURCE_FORMAT_R16G16B16A16_FLOAT:
    case RESOURCE_FORMAT_B8G8R8A8_TYPELESS:
    case RESOURCE_FORMAT_B8G8R8A8_UNORM:
    case RESOURCE_FORMAT_B8G8R8A8_UNORM_SRGB:
    case RESOURCE_FORMAT_X6Y10X6U10X6Y10X6V10_422_UNORM:
    case RESOURCE_FORMAT_Y16U16Y16V16_422_UNORM:
    case RESOURCE_FORMAT_BC1_TYPELESS:
    case RESOURCE_FORMAT_BC1_UNORM:
    case RESOURCE_FORMAT_BC1_UNORM_SRGB:
    case RESOURCE_FORMAT_BC4_TYPELESS:
    case RESOURCE_FORMAT_BC4_UNORM:
    case RESOURCE_FORMAT_BC4_SNORM:
    case RESOURCE_FORMAT_Y8_U8V8_2PLANE_420_UNORM_PLANE0:
    case RESOURCE_FORMAT_BC1_RGB_TYPELESS_BLOCK_VK:
    case RESOURCE_FORMAT_BC1_RGB_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_BC1_RGB_SRGB_BLOCK_VK:
    case RESOURCE_FORMAT_ETC2_R8G8B8_TYPELESS_BLOCK_VK:
    case RESOURCE_FORMAT_ETC2_R8G8B8_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_ETC2_R8G8B8_SRGB_BLOCK_VK:
    case RESOURCE_FORMAT_ETC2_R8G8B8A1_TYPELESS_BLOCK_VK:
    case RESOURCE_FORMAT_ETC2_R8G8B8A1_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_ETC2_R8G8B8A1_SRGB_BLOCK_VK:
    case RESOURCE_FORMAT_ETC2_R8G8B8A8_TYPELESS_BLOCK_VK:
    case RESOURCE_FORMAT_ETC2_R8G8B8A8_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_ETC2_R8G8B8A8_SRGB_BLOCK_VK:
    case RESOURCE_FORMAT_EAC_R11_TYPELESS_BLOCK_VK:
    case RESOURCE_FORMAT_EAC_R11_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_EAC_R11_SNORM_BLOCK_VK:
    case RESOURCE_FORMAT_PVRTC1_2BPP_UNORM_BLOCK_IMG_VK:
    case RESOURCE_FORMAT_PVRTC1_4BPP_UNORM_BLOCK_IMG_VK:
    case RESOURCE_FORMAT_PVRTC2_2BPP_UNORM_BLOCK_IMG_VK:
    case RESOURCE_FORMAT_PVRTC2_4BPP_UNORM_BLOCK_IMG_VK:
    case RESOURCE_FORMAT_PVRTC1_2BPP_SRGB_BLOCK_IMG_VK:
    case RESOURCE_FORMAT_PVRTC1_4BPP_SRGB_BLOCK_IMG_VK:
    case RESOURCE_FORMAT_PVRTC2_2BPP_SRGB_BLOCK_IMG_VK:
    case RESOURCE_FORMAT_PVRTC2_4BPP_SRGB_BLOCK_IMG_VK:
        return 8;

    case RESOURCE_FORMAT_R32G32B32_TYPELESS:
    case RESOURCE_FORMAT_R32G32B32_UINT:
    case RESOURCE_FORMAT_R32G32B32_SINT:
    case RESOURCE_FORMAT_R32G32B32_FLOAT:
        return 12;

    case RESOURCE_FORMAT_R32G32B32A32_TYPELESS:
    case RESOURCE_FORMAT_R32G32B32A32_UINT:
    case RESOURCE_FORMAT_R32G32B32A32_SINT:
    case RESOURCE_FORMAT_R32G32B32A32_FLOAT:
    case RESOURCE_FORMAT_BC2_TYPELESS:
    case RESOURCE_FORMAT_BC2_UNORM:
    case RESOURCE_FORMAT_BC2_UNORM_SRGB:
    case RESOURCE_FORMAT_BC3_TYPELESS:
    case RESOURCE_FORMAT_BC3_UNORM:
    case RESOURCE_FORMAT_BC3_UNORM_SRGB:
    case RESOURCE_FORMAT_BC5_TYPELESS:
    case RESOURCE_FORMAT_BC5_UNORM:
    case RESOURCE_FORMAT_BC5_SNORM:
    case RESOURCE_FORMAT_BC6H_TYPELESS:
    case RESOURCE_FORMAT_BC6H_UF16:
    case RESOURCE_FORMAT_BC6H_SF16:
    case RESOURCE_FORMAT_BC7_TYPELESS:
    case RESOURCE_FORMAT_BC7_UNORM:
    case RESOURCE_FORMAT_BC7_UNORM_SRGB:
    case RESOURCE_FORMAT_Y8_U8V8_2PLANE_420_UNORM_PLANE1:
    case RESOURCE_FORMAT_X6Y10_X6U10X6V10_2PLANE_420_UNORM_PLANE0:
    case RESOURCE_FORMAT_Y16_U16V16_2PLANE_420_UNORM_PLANE0:
    case RESOURCE_FORMAT_EAC_R11G11_TYPELESS_BLOCK_VK:
    case RESOURCE_FORMAT_EAC_R11G11_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_EAC_R11G11_SNORM_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_4x4_TYPELESS_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_4x4_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_4x4_SRGB_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_4x4_SFLOAT_BLOCK_EXT_VK:
    case RESOURCE_FORMAT_ASTC_5x4_TYPELESS_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_5x4_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_5x4_SRGB_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_5x4_SFLOAT_BLOCK_EXT_VK:
    case RESOURCE_FORMAT_ASTC_5x5_TYPELESS_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_5x5_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_5x5_SRGB_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_5x5_SFLOAT_BLOCK_EXT_VK:
    case RESOURCE_FORMAT_ASTC_6x5_TYPELESS_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_6x5_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_6x5_SRGB_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_6x5_SFLOAT_BLOCK_EXT_VK:
    case RESOURCE_FORMAT_ASTC_6x6_TYPELESS_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_6x6_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_6x6_SRGB_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_6x6_SFLOAT_BLOCK_EXT_VK:
    case RESOURCE_FORMAT_ASTC_8x5_TYPELESS_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_8x5_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_8x5_SRGB_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_8x5_SFLOAT_BLOCK_EXT_VK:
    case RESOURCE_FORMAT_ASTC_8x6_TYPELESS_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_8x6_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_8x6_SRGB_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_8x6_SFLOAT_BLOCK_EXT_VK:
    case RESOURCE_FORMAT_ASTC_8x8_TYPELESS_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_8x8_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_8x8_SRGB_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_8x8_SFLOAT_BLOCK_EXT_VK:
    case RESOURCE_FORMAT_ASTC_10x5_TYPELESS_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_10x5_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_10x5_SRGB_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_10x5_SFLOAT_BLOCK_EXT_VK:
    case RESOURCE_FORMAT_ASTC_10x6_TYPELESS_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_10x6_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_10x6_SRGB_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_10x6_SFLOAT_BLOCK_EXT_VK:
    case RESOURCE_FORMAT_ASTC_10x8_TYPELESS_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_10x8_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_10x8_SRGB_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_10x8_SFLOAT_BLOCK_EXT_VK:
    case RESOURCE_FORMAT_ASTC_10x10_TYPELESS_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_10x10_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_10x10_SRGB_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_10x10_SFLOAT_BLOCK_EXT_VK:
    case RESOURCE_FORMAT_ASTC_12x10_TYPELESS_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_12x10_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_12x10_SRGB_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_12x10_SFLOAT_BLOCK_EXT_VK:
    case RESOURCE_FORMAT_ASTC_12x12_TYPELESS_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_12x12_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_12x12_SRGB_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_12x12_SFLOAT_BLOCK_EXT_VK:
        return 16;

    default:
        return 0;
    }
}

size_t GetDepthOrStencilFormatSize(RESOURCE_FORMAT _format, bool _is_stencil)
{
    /*
    data copied to or from the stencil aspect of any depth/stencil format is tightly packed with one VK_FORMAT_S8_UINT value per texel.
    data copied to or from the depth aspect of a VK_FORMAT_D16_UNORM or VK_FORMAT_D16_UNORM_S8_UINT format is tightly packed with one VK_FORMAT_D16_UNORM value per texel.
    data copied to or from the depth aspect of a VK_FORMAT_D32_SFLOAT or VK_FORMAT_D32_SFLOAT_S8_UINT format is tightly packed with one VK_FORMAT_D32_SFLOAT value per texel.
    data copied to or from the depth aspect of a VK_FORMAT_X8_D24_UNORM_PACK32 or VK_FORMAT_D24_UNORM_S8_UINT format is packed with one 32-bit word per texel with the D24 value in the LSBs of the word, and undefined values in the eight MSBs.
    */
    switch (_format)
    {
    case buma3d::RESOURCE_FORMAT_D16_UNORM            : return _is_stencil ? 0 : 16;
    case buma3d::RESOURCE_FORMAT_D32_FLOAT            : return _is_stencil ? 0 : 32;
    case buma3d::RESOURCE_FORMAT_D24_UNORM_S8_UINT    : return _is_stencil ? 8 : 32;
    case buma3d::RESOURCE_FORMAT_D32_FLOAT_S8X24_UINT : return _is_stencil ? 8 : 32;

    default:
        return 0;
    }
}

void GetFormatBlockSize(RESOURCE_FORMAT _format, uint32_t* _dst_block_w, uint32_t* _dst_block_h)
{
    switch (_format)
    {
    case RESOURCE_FORMAT_R8_TYPELESS:
    case RESOURCE_FORMAT_R8_UNORM:
    case RESOURCE_FORMAT_R8_SNORM:
    case RESOURCE_FORMAT_R8_UINT:
    case RESOURCE_FORMAT_R8_SINT:

    case RESOURCE_FORMAT_R16_TYPELESS:
    case RESOURCE_FORMAT_R16_UNORM:
    case RESOURCE_FORMAT_R16_SNORM:
    case RESOURCE_FORMAT_R16_UINT:
    case RESOURCE_FORMAT_R16_SINT:
    case RESOURCE_FORMAT_R16_FLOAT:

    case RESOURCE_FORMAT_R32_TYPELESS:
    case RESOURCE_FORMAT_R32_UINT:
    case RESOURCE_FORMAT_R32_SINT:
    case RESOURCE_FORMAT_R32_FLOAT:

    case RESOURCE_FORMAT_R8G8_TYPELESS:
    case RESOURCE_FORMAT_R8G8_UNORM:
    case RESOURCE_FORMAT_R8G8_SNORM:
    case RESOURCE_FORMAT_R8G8_UINT:
    case RESOURCE_FORMAT_R8G8_SINT:

    case RESOURCE_FORMAT_R16G16_TYPELESS:
    case RESOURCE_FORMAT_R16G16_UNORM:
    case RESOURCE_FORMAT_R16G16_SNORM:
    case RESOURCE_FORMAT_R16G16_UINT:
    case RESOURCE_FORMAT_R16G16_SINT:
    case RESOURCE_FORMAT_R16G16_FLOAT:

    case RESOURCE_FORMAT_R32G32_TYPELESS:
    case RESOURCE_FORMAT_R32G32_UINT:
    case RESOURCE_FORMAT_R32G32_SINT:
    case RESOURCE_FORMAT_R32G32_FLOAT:

    case RESOURCE_FORMAT_R11G11B10_UFLOAT:

    case RESOURCE_FORMAT_R32G32B32_TYPELESS:
    case RESOURCE_FORMAT_R32G32B32_UINT:
    case RESOURCE_FORMAT_R32G32B32_SINT:
    case RESOURCE_FORMAT_R32G32B32_FLOAT:

    case RESOURCE_FORMAT_B5G6R5_UNORM:

    case RESOURCE_FORMAT_R8G8B8A8_TYPELESS:
    case RESOURCE_FORMAT_R8G8B8A8_UNORM:
    case RESOURCE_FORMAT_R8G8B8A8_UNORM_SRGB:
    case RESOURCE_FORMAT_R8G8B8A8_SNORM:
    case RESOURCE_FORMAT_R8G8B8A8_UINT:
    case RESOURCE_FORMAT_R8G8B8A8_SINT:

    case RESOURCE_FORMAT_R10G10B10A2_TYPELESS:
    case RESOURCE_FORMAT_R10G10B10A2_UNORM:
    case RESOURCE_FORMAT_R10G10B10A2_UINT:

    case RESOURCE_FORMAT_R16G16B16A16_TYPELESS:
    case RESOURCE_FORMAT_R16G16B16A16_UNORM:
    case RESOURCE_FORMAT_R16G16B16A16_SNORM:
    case RESOURCE_FORMAT_R16G16B16A16_UINT:
    case RESOURCE_FORMAT_R16G16B16A16_SINT:
    case RESOURCE_FORMAT_R16G16B16A16_FLOAT:

    case RESOURCE_FORMAT_R32G32B32A32_TYPELESS:
    case RESOURCE_FORMAT_R32G32B32A32_UINT:
    case RESOURCE_FORMAT_R32G32B32A32_SINT:
    case RESOURCE_FORMAT_R32G32B32A32_FLOAT:

    case RESOURCE_FORMAT_B5G5R5A1_UNORM:

    case RESOURCE_FORMAT_B8G8R8A8_TYPELESS:
    case RESOURCE_FORMAT_B8G8R8A8_UNORM:
    case RESOURCE_FORMAT_B8G8R8A8_UNORM_SRGB:

    case RESOURCE_FORMAT_R9G9B9E5_UFLOAT:
    case RESOURCE_FORMAT_D16_UNORM:
    case RESOURCE_FORMAT_D32_FLOAT:
    case RESOURCE_FORMAT_D24_UNORM_S8_UINT:
    case RESOURCE_FORMAT_D32_FLOAT_S8X24_UINT:
        *_dst_block_w = 1;
        *_dst_block_h = 1;
        break;
    
    case RESOURCE_FORMAT_Y8U8Y8V8_422_UNORM:
    case RESOURCE_FORMAT_X6Y10X6U10X6Y10X6V10_422_UNORM:
    case RESOURCE_FORMAT_Y16U16Y16V16_422_UNORM:
        *_dst_block_w = 2;
        *_dst_block_h = 1;
        break;

    case RESOURCE_FORMAT_Y8_U8V8_2PLANE_420_UNORM:
    case RESOURCE_FORMAT_Y8_U8V8_2PLANE_420_UNORM_PLANE0:
    case RESOURCE_FORMAT_Y8_U8V8_2PLANE_420_UNORM_PLANE1:
    case RESOURCE_FORMAT_X6Y10_X6U10X6V10_2PLANE_420_UNORM:
    case RESOURCE_FORMAT_X6Y10_X6U10X6V10_2PLANE_420_UNORM_PLANE0:
    case RESOURCE_FORMAT_X6Y10_X6U10X6V10_2PLANE_420_UNORM_PLANE1:
    case RESOURCE_FORMAT_Y16_U16V16_2PLANE_420_UNORM:
    case RESOURCE_FORMAT_Y16_U16V16_2PLANE_420_UNORM_PLANE0:
    case RESOURCE_FORMAT_Y16_U16V16_2PLANE_420_UNORM_PLANE1:
        *_dst_block_w = 2;
        *_dst_block_h = 2;
        break;

    case RESOURCE_FORMAT_BC1_TYPELESS:
    case RESOURCE_FORMAT_BC1_UNORM:
    case RESOURCE_FORMAT_BC1_UNORM_SRGB:

    case RESOURCE_FORMAT_BC2_TYPELESS:
    case RESOURCE_FORMAT_BC2_UNORM:
    case RESOURCE_FORMAT_BC2_UNORM_SRGB:

    case RESOURCE_FORMAT_BC3_TYPELESS:
    case RESOURCE_FORMAT_BC3_UNORM:
    case RESOURCE_FORMAT_BC3_UNORM_SRGB:

    case RESOURCE_FORMAT_BC4_TYPELESS:
    case RESOURCE_FORMAT_BC4_UNORM:
    case RESOURCE_FORMAT_BC4_SNORM:

    case RESOURCE_FORMAT_BC5_TYPELESS:
    case RESOURCE_FORMAT_BC5_UNORM:
    case RESOURCE_FORMAT_BC5_SNORM:

    case RESOURCE_FORMAT_BC6H_TYPELESS:
    case RESOURCE_FORMAT_BC6H_UF16:
    case RESOURCE_FORMAT_BC6H_SF16:

    case RESOURCE_FORMAT_BC7_TYPELESS:
    case RESOURCE_FORMAT_BC7_UNORM:
    case RESOURCE_FORMAT_BC7_UNORM_SRGB:

    case RESOURCE_FORMAT_BC1_RGB_TYPELESS_BLOCK_VK:
    case RESOURCE_FORMAT_BC1_RGB_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_BC1_RGB_SRGB_BLOCK_VK:

    case RESOURCE_FORMAT_ETC2_R8G8B8_TYPELESS_BLOCK_VK:
    case RESOURCE_FORMAT_ETC2_R8G8B8_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_ETC2_R8G8B8_SRGB_BLOCK_VK:

    case RESOURCE_FORMAT_ETC2_R8G8B8A1_TYPELESS_BLOCK_VK:
    case RESOURCE_FORMAT_ETC2_R8G8B8A1_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_ETC2_R8G8B8A1_SRGB_BLOCK_VK:

    case RESOURCE_FORMAT_ETC2_R8G8B8A8_TYPELESS_BLOCK_VK:
    case RESOURCE_FORMAT_ETC2_R8G8B8A8_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_ETC2_R8G8B8A8_SRGB_BLOCK_VK:

    case RESOURCE_FORMAT_EAC_R11_TYPELESS_BLOCK_VK:
    case RESOURCE_FORMAT_EAC_R11_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_EAC_R11_SNORM_BLOCK_VK:

    case RESOURCE_FORMAT_EAC_R11G11_TYPELESS_BLOCK_VK:
    case RESOURCE_FORMAT_EAC_R11G11_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_EAC_R11G11_SNORM_BLOCK_VK:

    case RESOURCE_FORMAT_ASTC_4x4_TYPELESS_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_4x4_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_4x4_SRGB_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_4x4_SFLOAT_BLOCK_EXT_VK:

    case RESOURCE_FORMAT_PVRTC1_4BPP_UNORM_BLOCK_IMG_VK:
    case RESOURCE_FORMAT_PVRTC1_4BPP_SRGB_BLOCK_IMG_VK:
    case RESOURCE_FORMAT_PVRTC2_4BPP_UNORM_BLOCK_IMG_VK:
    case RESOURCE_FORMAT_PVRTC2_4BPP_SRGB_BLOCK_IMG_VK:
        *_dst_block_w = 4;
        *_dst_block_h = 4;
        break;

    case RESOURCE_FORMAT_ASTC_5x4_TYPELESS_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_5x4_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_5x4_SRGB_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_5x4_SFLOAT_BLOCK_EXT_VK:
        *_dst_block_w = 5;
        *_dst_block_h = 4;
        break;

    case RESOURCE_FORMAT_ASTC_5x5_TYPELESS_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_5x5_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_5x5_SRGB_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_5x5_SFLOAT_BLOCK_EXT_VK:
        *_dst_block_w = 5;
        *_dst_block_h = 5;
        break;

    case RESOURCE_FORMAT_ASTC_6x5_TYPELESS_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_6x5_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_6x5_SRGB_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_6x5_SFLOAT_BLOCK_EXT_VK:
        *_dst_block_w = 6;
        *_dst_block_h = 5;
        break;

    case RESOURCE_FORMAT_ASTC_6x6_TYPELESS_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_6x6_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_6x6_SRGB_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_6x6_SFLOAT_BLOCK_EXT_VK:
        *_dst_block_w = 6;
        *_dst_block_h = 6;
        break;

    case RESOURCE_FORMAT_ASTC_8x5_TYPELESS_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_8x5_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_8x5_SRGB_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_8x5_SFLOAT_BLOCK_EXT_VK:
        *_dst_block_w = 8;
        *_dst_block_h = 5;
        break;

    case RESOURCE_FORMAT_ASTC_8x6_TYPELESS_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_8x6_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_8x6_SRGB_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_8x6_SFLOAT_BLOCK_EXT_VK:
        *_dst_block_w = 8;
        *_dst_block_h = 6;
        break;

    case RESOURCE_FORMAT_ASTC_8x8_TYPELESS_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_8x8_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_8x8_SRGB_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_8x8_SFLOAT_BLOCK_EXT_VK:
        *_dst_block_w = 8;
        *_dst_block_h = 8;
        break;

    case RESOURCE_FORMAT_ASTC_10x5_TYPELESS_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_10x5_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_10x5_SRGB_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_10x5_SFLOAT_BLOCK_EXT_VK:
        *_dst_block_w = 10;
        *_dst_block_h = 5;
        break;

    case RESOURCE_FORMAT_ASTC_10x6_TYPELESS_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_10x6_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_10x6_SRGB_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_10x6_SFLOAT_BLOCK_EXT_VK:
        *_dst_block_w = 10;
        *_dst_block_h = 6;
        break;

    case RESOURCE_FORMAT_ASTC_10x8_TYPELESS_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_10x8_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_10x8_SRGB_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_10x8_SFLOAT_BLOCK_EXT_VK:
        *_dst_block_w = 10;
        *_dst_block_h = 8;
        break;

    case RESOURCE_FORMAT_ASTC_10x10_TYPELESS_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_10x10_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_10x10_SRGB_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_10x10_SFLOAT_BLOCK_EXT_VK:
        *_dst_block_w = 10;
        *_dst_block_h = 10;
        break;

    case RESOURCE_FORMAT_ASTC_12x10_TYPELESS_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_12x10_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_12x10_SRGB_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_12x10_SFLOAT_BLOCK_EXT_VK:
        *_dst_block_w = 12;
        *_dst_block_h = 10;
        break;

    case RESOURCE_FORMAT_ASTC_12x12_TYPELESS_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_12x12_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_12x12_SRGB_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_12x12_SFLOAT_BLOCK_EXT_VK:
        *_dst_block_w = 12;
        *_dst_block_h = 12;
        break;

    case RESOURCE_FORMAT_PVRTC1_2BPP_UNORM_BLOCK_IMG_VK:
    case RESOURCE_FORMAT_PVRTC2_2BPP_UNORM_BLOCK_IMG_VK:
    case RESOURCE_FORMAT_PVRTC1_2BPP_SRGB_BLOCK_IMG_VK:
    case RESOURCE_FORMAT_PVRTC2_2BPP_SRGB_BLOCK_IMG_VK:
        *_dst_block_w = 8;
        *_dst_block_h = 4;
        break;

    default:
        *_dst_block_w = 0;
        *_dst_block_w = 0;
        break;
    }
}

RESOURCE_FORMAT GetTypelessFormat(RESOURCE_FORMAT _format)
{
    switch (_format)
    {
    case RESOURCE_FORMAT_R8_UNORM:
    case RESOURCE_FORMAT_R8_SNORM:
    case RESOURCE_FORMAT_R8_UINT:
    case RESOURCE_FORMAT_R8_SINT:
        return RESOURCE_FORMAT_R8_TYPELESS;

    case RESOURCE_FORMAT_R16_UNORM:
    case RESOURCE_FORMAT_R16_SNORM:
    case RESOURCE_FORMAT_R16_UINT:
    case RESOURCE_FORMAT_R16_SINT:
    case RESOURCE_FORMAT_R16_FLOAT:
        return RESOURCE_FORMAT_R16_TYPELESS;

    case RESOURCE_FORMAT_R32_UINT:
    case RESOURCE_FORMAT_R32_SINT:
    case RESOURCE_FORMAT_R32_FLOAT:
        return RESOURCE_FORMAT_R32_TYPELESS;

    case RESOURCE_FORMAT_R8G8_UNORM:
    case RESOURCE_FORMAT_R8G8_SNORM:
    case RESOURCE_FORMAT_R8G8_UINT:
    case RESOURCE_FORMAT_R8G8_SINT:
        return RESOURCE_FORMAT_R8G8_TYPELESS;

    case RESOURCE_FORMAT_R16G16_UNORM:
    case RESOURCE_FORMAT_R16G16_SNORM:
    case RESOURCE_FORMAT_R16G16_UINT:
    case RESOURCE_FORMAT_R16G16_SINT:
    case RESOURCE_FORMAT_R16G16_FLOAT:
        return RESOURCE_FORMAT_R16G16_TYPELESS;

    case RESOURCE_FORMAT_R32G32_UINT:
    case RESOURCE_FORMAT_R32G32_SINT:
    case RESOURCE_FORMAT_R32G32_FLOAT:
    case RESOURCE_FORMAT_R11G11B10_UFLOAT:
        return RESOURCE_FORMAT_R32G32_TYPELESS;

    case RESOURCE_FORMAT_R32G32B32_UINT:
    case RESOURCE_FORMAT_R32G32B32_SINT:
    case RESOURCE_FORMAT_R32G32B32_FLOAT:
    case RESOURCE_FORMAT_B5G6R5_UNORM:
        return RESOURCE_FORMAT_R32G32B32_TYPELESS;

    case RESOURCE_FORMAT_R8G8B8A8_UNORM:
    case RESOURCE_FORMAT_R8G8B8A8_UNORM_SRGB:
    case RESOURCE_FORMAT_R8G8B8A8_SNORM:
    case RESOURCE_FORMAT_R8G8B8A8_UINT:
    case RESOURCE_FORMAT_R8G8B8A8_SINT:
        return RESOURCE_FORMAT_R8G8B8A8_TYPELESS;

    case RESOURCE_FORMAT_R10G10B10A2_UNORM:
    case RESOURCE_FORMAT_R10G10B10A2_UINT:
        return RESOURCE_FORMAT_R10G10B10A2_TYPELESS;

    case RESOURCE_FORMAT_R16G16B16A16_UNORM:
    case RESOURCE_FORMAT_R16G16B16A16_SNORM:
    case RESOURCE_FORMAT_R16G16B16A16_UINT:
    case RESOURCE_FORMAT_R16G16B16A16_SINT:
    case RESOURCE_FORMAT_R16G16B16A16_FLOAT:
        return RESOURCE_FORMAT_R16G16B16A16_TYPELESS;

    case RESOURCE_FORMAT_R32G32B32A32_UINT:
    case RESOURCE_FORMAT_R32G32B32A32_SINT:
    case RESOURCE_FORMAT_R32G32B32A32_FLOAT:
    case RESOURCE_FORMAT_B5G5R5A1_UNORM:
        return RESOURCE_FORMAT_R32G32B32A32_TYPELESS;

    case RESOURCE_FORMAT_B8G8R8A8_UNORM:
    case RESOURCE_FORMAT_B8G8R8A8_UNORM_SRGB:
    case RESOURCE_FORMAT_R9G9B9E5_UFLOAT:
    case RESOURCE_FORMAT_D16_UNORM:
    case RESOURCE_FORMAT_D32_FLOAT:
    case RESOURCE_FORMAT_D24_UNORM_S8_UINT:
    case RESOURCE_FORMAT_D32_FLOAT_S8X24_UINT:
        return RESOURCE_FORMAT_B8G8R8A8_TYPELESS;

    case RESOURCE_FORMAT_BC1_UNORM:
    case RESOURCE_FORMAT_BC1_UNORM_SRGB:
        return RESOURCE_FORMAT_BC1_TYPELESS;

    case RESOURCE_FORMAT_BC2_UNORM:
    case RESOURCE_FORMAT_BC2_UNORM_SRGB:
        return RESOURCE_FORMAT_BC2_TYPELESS;

    case RESOURCE_FORMAT_BC3_UNORM:
    case RESOURCE_FORMAT_BC3_UNORM_SRGB:
        return RESOURCE_FORMAT_BC3_TYPELESS;

    case RESOURCE_FORMAT_BC4_UNORM:
    case RESOURCE_FORMAT_BC4_SNORM:
        return RESOURCE_FORMAT_BC4_TYPELESS;

    case RESOURCE_FORMAT_BC5_UNORM:
    case RESOURCE_FORMAT_BC5_SNORM:
        return RESOURCE_FORMAT_BC5_TYPELESS;

    case RESOURCE_FORMAT_BC6H_UF16:
    case RESOURCE_FORMAT_BC6H_SF16:
        return RESOURCE_FORMAT_BC6H_TYPELESS;

    case RESOURCE_FORMAT_BC7_UNORM:
    case RESOURCE_FORMAT_BC7_UNORM_SRGB:
        return RESOURCE_FORMAT_BC7_TYPELESS;

    case RESOURCE_FORMAT_BC1_RGB_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_BC1_RGB_SRGB_BLOCK_VK:
        return RESOURCE_FORMAT_BC1_RGB_TYPELESS_BLOCK_VK;

    case RESOURCE_FORMAT_ETC2_R8G8B8_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_ETC2_R8G8B8_SRGB_BLOCK_VK:
        return RESOURCE_FORMAT_ETC2_R8G8B8_TYPELESS_BLOCK_VK;

    case RESOURCE_FORMAT_ETC2_R8G8B8A1_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_ETC2_R8G8B8A1_SRGB_BLOCK_VK:
        return RESOURCE_FORMAT_ETC2_R8G8B8A1_TYPELESS_BLOCK_VK;

    case RESOURCE_FORMAT_ETC2_R8G8B8A8_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_ETC2_R8G8B8A8_SRGB_BLOCK_VK:
        return RESOURCE_FORMAT_ETC2_R8G8B8A8_TYPELESS_BLOCK_VK;

    case RESOURCE_FORMAT_EAC_R11_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_EAC_R11_SNORM_BLOCK_VK:
        return RESOURCE_FORMAT_EAC_R11_TYPELESS_BLOCK_VK;

    case RESOURCE_FORMAT_EAC_R11G11_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_EAC_R11G11_SNORM_BLOCK_VK:
        return RESOURCE_FORMAT_EAC_R11G11_TYPELESS_BLOCK_VK;

    case RESOURCE_FORMAT_ASTC_4x4_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_4x4_SRGB_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_4x4_SFLOAT_BLOCK_EXT_VK:
        return RESOURCE_FORMAT_ASTC_4x4_TYPELESS_BLOCK_VK;

    case RESOURCE_FORMAT_ASTC_5x4_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_5x4_SRGB_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_5x4_SFLOAT_BLOCK_EXT_VK:
        return RESOURCE_FORMAT_ASTC_5x4_TYPELESS_BLOCK_VK;

    case RESOURCE_FORMAT_ASTC_5x5_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_5x5_SRGB_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_5x5_SFLOAT_BLOCK_EXT_VK:
        return RESOURCE_FORMAT_ASTC_5x5_TYPELESS_BLOCK_VK;

    case RESOURCE_FORMAT_ASTC_6x5_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_6x5_SRGB_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_6x5_SFLOAT_BLOCK_EXT_VK:
        return RESOURCE_FORMAT_ASTC_6x5_TYPELESS_BLOCK_VK;

    case RESOURCE_FORMAT_ASTC_6x6_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_6x6_SRGB_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_6x6_SFLOAT_BLOCK_EXT_VK:
        return RESOURCE_FORMAT_ASTC_6x6_TYPELESS_BLOCK_VK;

    case RESOURCE_FORMAT_ASTC_8x5_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_8x5_SRGB_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_8x5_SFLOAT_BLOCK_EXT_VK:
        return RESOURCE_FORMAT_ASTC_8x5_TYPELESS_BLOCK_VK;

    case RESOURCE_FORMAT_ASTC_8x6_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_8x6_SRGB_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_8x6_SFLOAT_BLOCK_EXT_VK:
        return RESOURCE_FORMAT_ASTC_8x6_TYPELESS_BLOCK_VK;

    case RESOURCE_FORMAT_ASTC_8x8_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_8x8_SRGB_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_8x8_SFLOAT_BLOCK_EXT_VK:
        return RESOURCE_FORMAT_ASTC_8x8_TYPELESS_BLOCK_VK;

    case RESOURCE_FORMAT_ASTC_10x5_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_10x5_SRGB_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_10x5_SFLOAT_BLOCK_EXT_VK:
        return RESOURCE_FORMAT_ASTC_10x5_TYPELESS_BLOCK_VK;

    case RESOURCE_FORMAT_ASTC_10x6_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_10x6_SRGB_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_10x6_SFLOAT_BLOCK_EXT_VK:
        return RESOURCE_FORMAT_ASTC_10x6_TYPELESS_BLOCK_VK;

    case RESOURCE_FORMAT_ASTC_10x8_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_10x8_SRGB_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_10x8_SFLOAT_BLOCK_EXT_VK:
        return RESOURCE_FORMAT_ASTC_10x8_TYPELESS_BLOCK_VK;

    case RESOURCE_FORMAT_ASTC_10x10_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_10x10_SRGB_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_10x10_SFLOAT_BLOCK_EXT_VK:
        return RESOURCE_FORMAT_ASTC_10x10_TYPELESS_BLOCK_VK;

    case RESOURCE_FORMAT_ASTC_12x10_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_12x10_SRGB_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_12x10_SFLOAT_BLOCK_EXT_VK:
        return RESOURCE_FORMAT_ASTC_12x10_TYPELESS_BLOCK_VK;

    case RESOURCE_FORMAT_ASTC_12x12_UNORM_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_12x12_SRGB_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_12x12_SFLOAT_BLOCK_EXT_VK:
        return RESOURCE_FORMAT_ASTC_12x12_TYPELESS_BLOCK_VK;

    default:
        return RESOURCE_FORMAT_UNKNOWN;
    }
}

bool IsTypelessFormat(RESOURCE_FORMAT _format)
{
    switch (_format)
    {
    case RESOURCE_FORMAT_R8_TYPELESS:
    case RESOURCE_FORMAT_R16_TYPELESS:
    case RESOURCE_FORMAT_R32_TYPELESS:
    case RESOURCE_FORMAT_R8G8_TYPELESS:
    case RESOURCE_FORMAT_R16G16_TYPELESS:
    case RESOURCE_FORMAT_R32G32_TYPELESS:
    case RESOURCE_FORMAT_R32G32B32_TYPELESS:
    case RESOURCE_FORMAT_R8G8B8A8_TYPELESS:
    case RESOURCE_FORMAT_R10G10B10A2_TYPELESS:
    case RESOURCE_FORMAT_R16G16B16A16_TYPELESS:
    case RESOURCE_FORMAT_R32G32B32A32_TYPELESS:
    case RESOURCE_FORMAT_B8G8R8A8_TYPELESS:
    case RESOURCE_FORMAT_BC1_TYPELESS:
    case RESOURCE_FORMAT_BC2_TYPELESS:
    case RESOURCE_FORMAT_BC3_TYPELESS:
    case RESOURCE_FORMAT_BC4_TYPELESS:
    case RESOURCE_FORMAT_BC5_TYPELESS:
    case RESOURCE_FORMAT_BC6H_TYPELESS:
    case RESOURCE_FORMAT_BC7_TYPELESS:
    case RESOURCE_FORMAT_BC1_RGB_TYPELESS_BLOCK_VK:
    case RESOURCE_FORMAT_ETC2_R8G8B8_TYPELESS_BLOCK_VK:
    case RESOURCE_FORMAT_ETC2_R8G8B8A1_TYPELESS_BLOCK_VK:
    case RESOURCE_FORMAT_ETC2_R8G8B8A8_TYPELESS_BLOCK_VK:
    case RESOURCE_FORMAT_EAC_R11_TYPELESS_BLOCK_VK:
    case RESOURCE_FORMAT_EAC_R11G11_TYPELESS_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_4x4_TYPELESS_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_5x4_TYPELESS_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_5x5_TYPELESS_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_6x5_TYPELESS_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_6x6_TYPELESS_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_8x5_TYPELESS_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_8x6_TYPELESS_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_8x8_TYPELESS_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_10x5_TYPELESS_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_10x6_TYPELESS_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_10x8_TYPELESS_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_10x10_TYPELESS_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_12x10_TYPELESS_BLOCK_VK:
    case RESOURCE_FORMAT_ASTC_12x12_TYPELESS_BLOCK_VK:
        return true;

    default:
        return false;
    }
}

bool IsDepthStencilFormat(RESOURCE_FORMAT _format)
{
    switch (_format)
    {
    case buma3d::RESOURCE_FORMAT_D16_UNORM:
    case buma3d::RESOURCE_FORMAT_D32_FLOAT:
    case buma3d::RESOURCE_FORMAT_D24_UNORM_S8_UINT:
    case buma3d::RESOURCE_FORMAT_D32_FLOAT_S8X24_UINT:
        return true;
    default:
        return false;
    }
}

bool IsDepthOnlyFormat(RESOURCE_FORMAT _format)
{
    switch (_format)
    {
    case buma3d::RESOURCE_FORMAT_D16_UNORM:
    case buma3d::RESOURCE_FORMAT_D32_FLOAT:
        return true;
    default:
        return false;
    }
}

bool IsMultiplanarFormat(RESOURCE_FORMAT _format)
{
    // NOTE: 深度ステンシルフォーマットはmulti-planarとして扱いません。 代わりにDEPTHまたはSTENCILアスペクトを使用します
    switch (_format)
    {
    case RESOURCE_FORMAT_Y8U8Y8V8_422_UNORM:
    case RESOURCE_FORMAT_X6Y10X6U10X6Y10X6V10_422_UNORM:
    case RESOURCE_FORMAT_Y16U16Y16V16_422_UNORM:
    case RESOURCE_FORMAT_Y8_U8V8_2PLANE_420_UNORM:
    case RESOURCE_FORMAT_X6Y10_X6U10X6V10_2PLANE_420_UNORM:
    case RESOURCE_FORMAT_Y16_U16V16_2PLANE_420_UNORM:
        return true;

    default:
        return false;
    }
}

size_t GetPlaneCount(RESOURCE_FORMAT _format)
{
    switch (_format)
    {
    case RESOURCE_FORMAT_Y8U8Y8V8_422_UNORM                : return 1;
    case RESOURCE_FORMAT_X6Y10X6U10X6Y10X6V10_422_UNORM    : return 1;
    case RESOURCE_FORMAT_Y16U16Y16V16_422_UNORM            : return 1;
    case RESOURCE_FORMAT_Y8_U8V8_2PLANE_420_UNORM          : return 2;
    case RESOURCE_FORMAT_X6Y10_X6U10X6V10_2PLANE_420_UNORM : return 2;
    case RESOURCE_FORMAT_Y16_U16V16_2PLANE_420_UNORM       : return 2;

    default:
        return 1;
    }
}

bool IsIntegerFormat(RESOURCE_FORMAT _format)
{
    switch (_format)
    {
    case buma3d::RESOURCE_FORMAT_R8_UINT:
    case buma3d::RESOURCE_FORMAT_R8_SINT:
    case buma3d::RESOURCE_FORMAT_R16_UINT:
    case buma3d::RESOURCE_FORMAT_R16_SINT:
    case buma3d::RESOURCE_FORMAT_R32_UINT:
    case buma3d::RESOURCE_FORMAT_R32_SINT:
    case buma3d::RESOURCE_FORMAT_R8G8_UINT:
    case buma3d::RESOURCE_FORMAT_R8G8_SINT:
    case buma3d::RESOURCE_FORMAT_R16G16_UINT:
    case buma3d::RESOURCE_FORMAT_R16G16_SINT:
    case buma3d::RESOURCE_FORMAT_R32G32_UINT:
    case buma3d::RESOURCE_FORMAT_R32G32_SINT:
    case buma3d::RESOURCE_FORMAT_R32G32B32_UINT:
    case buma3d::RESOURCE_FORMAT_R32G32B32_SINT:
    case buma3d::RESOURCE_FORMAT_R8G8B8A8_UINT:
    case buma3d::RESOURCE_FORMAT_R8G8B8A8_SINT:
    case buma3d::RESOURCE_FORMAT_R10G10B10A2_UINT:
    case buma3d::RESOURCE_FORMAT_R16G16B16A16_UINT:
    case buma3d::RESOURCE_FORMAT_R16G16B16A16_SINT:
    case buma3d::RESOURCE_FORMAT_R32G32B32A32_UINT:
    case buma3d::RESOURCE_FORMAT_R32G32B32A32_SINT:
    case buma3d::RESOURCE_FORMAT_D24_UNORM_S8_UINT:
    case buma3d::RESOURCE_FORMAT_D32_FLOAT_S8X24_UINT:
        return true;

    case buma3d::RESOURCE_FORMAT_BC1_TYPELESS:
    case buma3d::RESOURCE_FORMAT_BC1_UNORM:
    case buma3d::RESOURCE_FORMAT_BC1_UNORM_SRGB:
    case buma3d::RESOURCE_FORMAT_BC2_TYPELESS:
    case buma3d::RESOURCE_FORMAT_BC2_UNORM:
    case buma3d::RESOURCE_FORMAT_BC2_UNORM_SRGB:
    case buma3d::RESOURCE_FORMAT_BC3_TYPELESS:
    case buma3d::RESOURCE_FORMAT_BC3_UNORM:
    case buma3d::RESOURCE_FORMAT_BC3_UNORM_SRGB:
    case buma3d::RESOURCE_FORMAT_BC4_TYPELESS:
    case buma3d::RESOURCE_FORMAT_BC4_UNORM:
    case buma3d::RESOURCE_FORMAT_BC4_SNORM:
    case buma3d::RESOURCE_FORMAT_BC5_TYPELESS:
    case buma3d::RESOURCE_FORMAT_BC5_UNORM:
    case buma3d::RESOURCE_FORMAT_BC5_SNORM:
    case buma3d::RESOURCE_FORMAT_BC6H_TYPELESS:
    case buma3d::RESOURCE_FORMAT_BC6H_UF16:
    case buma3d::RESOURCE_FORMAT_BC6H_SF16:
    case buma3d::RESOURCE_FORMAT_BC7_TYPELESS:
    case buma3d::RESOURCE_FORMAT_BC7_UNORM:
    case buma3d::RESOURCE_FORMAT_BC7_UNORM_SRGB:
    case buma3d::RESOURCE_FORMAT_Y8U8Y8V8_422_UNORM:
    case buma3d::RESOURCE_FORMAT_X6Y10X6U10X6Y10X6V10_422_UNORM:
    case buma3d::RESOURCE_FORMAT_Y16U16Y16V16_422_UNORM:
    case buma3d::RESOURCE_FORMAT_Y8_U8V8_2PLANE_420_UNORM:
    case buma3d::RESOURCE_FORMAT_Y8_U8V8_2PLANE_420_UNORM_PLANE0:
    case buma3d::RESOURCE_FORMAT_Y8_U8V8_2PLANE_420_UNORM_PLANE1:
    case buma3d::RESOURCE_FORMAT_X6Y10_X6U10X6V10_2PLANE_420_UNORM:
    case buma3d::RESOURCE_FORMAT_X6Y10_X6U10X6V10_2PLANE_420_UNORM_PLANE0:
    case buma3d::RESOURCE_FORMAT_X6Y10_X6U10X6V10_2PLANE_420_UNORM_PLANE1:
    case buma3d::RESOURCE_FORMAT_Y16_U16V16_2PLANE_420_UNORM:
    case buma3d::RESOURCE_FORMAT_Y16_U16V16_2PLANE_420_UNORM_PLANE0:
    case buma3d::RESOURCE_FORMAT_Y16_U16V16_2PLANE_420_UNORM_PLANE1:
    case buma3d::RESOURCE_FORMAT_BC1_RGB_TYPELESS_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_BC1_RGB_UNORM_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_BC1_RGB_SRGB_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ETC2_R8G8B8_TYPELESS_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ETC2_R8G8B8_UNORM_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ETC2_R8G8B8_SRGB_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ETC2_R8G8B8A1_TYPELESS_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ETC2_R8G8B8A1_UNORM_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ETC2_R8G8B8A1_SRGB_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ETC2_R8G8B8A8_TYPELESS_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ETC2_R8G8B8A8_UNORM_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ETC2_R8G8B8A8_SRGB_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_EAC_R11_TYPELESS_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_EAC_R11_UNORM_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_EAC_R11_SNORM_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_EAC_R11G11_TYPELESS_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_EAC_R11G11_UNORM_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_EAC_R11G11_SNORM_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_4x4_TYPELESS_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_4x4_UNORM_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_4x4_SRGB_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_4x4_SFLOAT_BLOCK_EXT_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_5x4_TYPELESS_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_5x4_UNORM_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_5x4_SRGB_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_5x4_SFLOAT_BLOCK_EXT_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_5x5_TYPELESS_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_5x5_UNORM_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_5x5_SRGB_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_5x5_SFLOAT_BLOCK_EXT_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_6x5_TYPELESS_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_6x5_UNORM_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_6x5_SRGB_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_6x5_SFLOAT_BLOCK_EXT_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_6x6_TYPELESS_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_6x6_UNORM_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_6x6_SRGB_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_6x6_SFLOAT_BLOCK_EXT_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_8x5_TYPELESS_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_8x5_UNORM_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_8x5_SRGB_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_8x5_SFLOAT_BLOCK_EXT_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_8x6_TYPELESS_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_8x6_UNORM_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_8x6_SRGB_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_8x6_SFLOAT_BLOCK_EXT_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_8x8_TYPELESS_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_8x8_UNORM_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_8x8_SRGB_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_8x8_SFLOAT_BLOCK_EXT_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_10x5_TYPELESS_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_10x5_UNORM_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_10x5_SRGB_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_10x5_SFLOAT_BLOCK_EXT_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_10x6_TYPELESS_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_10x6_UNORM_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_10x6_SRGB_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_10x6_SFLOAT_BLOCK_EXT_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_10x8_TYPELESS_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_10x8_UNORM_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_10x8_SRGB_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_10x8_SFLOAT_BLOCK_EXT_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_10x10_TYPELESS_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_10x10_UNORM_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_10x10_SRGB_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_10x10_SFLOAT_BLOCK_EXT_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_12x10_TYPELESS_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_12x10_UNORM_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_12x10_SRGB_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_12x10_SFLOAT_BLOCK_EXT_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_12x12_TYPELESS_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_12x12_UNORM_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_12x12_SRGB_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_12x12_SFLOAT_BLOCK_EXT_VK:
    case buma3d::RESOURCE_FORMAT_PVRTC1_2BPP_UNORM_BLOCK_IMG_VK:
    case buma3d::RESOURCE_FORMAT_PVRTC1_4BPP_UNORM_BLOCK_IMG_VK:
    case buma3d::RESOURCE_FORMAT_PVRTC2_2BPP_UNORM_BLOCK_IMG_VK:
    case buma3d::RESOURCE_FORMAT_PVRTC2_4BPP_UNORM_BLOCK_IMG_VK:
    case buma3d::RESOURCE_FORMAT_PVRTC1_2BPP_SRGB_BLOCK_IMG_VK:
    case buma3d::RESOURCE_FORMAT_PVRTC1_4BPP_SRGB_BLOCK_IMG_VK:
    case buma3d::RESOURCE_FORMAT_PVRTC2_2BPP_SRGB_BLOCK_IMG_VK:
    case buma3d::RESOURCE_FORMAT_PVRTC2_4BPP_SRGB_BLOCK_IMG_VK:
        return false;

    default:
        return false;
    }
}

bool IsSintFormat(RESOURCE_FORMAT _format)
{
    switch (_format)
    {
    case buma3d::RESOURCE_FORMAT_R8_SINT:
    case buma3d::RESOURCE_FORMAT_R16_SINT:
    case buma3d::RESOURCE_FORMAT_R32_SINT:
    case buma3d::RESOURCE_FORMAT_R8G8_SINT:
    case buma3d::RESOURCE_FORMAT_R16G16_SINT:
    case buma3d::RESOURCE_FORMAT_R32G32_SINT:
    case buma3d::RESOURCE_FORMAT_R32G32B32_SINT:
    case buma3d::RESOURCE_FORMAT_R8G8B8A8_SINT:
    case buma3d::RESOURCE_FORMAT_R16G16B16A16_SINT:
    case buma3d::RESOURCE_FORMAT_R32G32B32A32_SINT:
        return true;

    default:
        return false;
    }
}

bool IsUintFormat(RESOURCE_FORMAT _format)
{
    switch (_format)
    {
    case buma3d::RESOURCE_FORMAT_R8_UINT:
    case buma3d::RESOURCE_FORMAT_R16_UINT:
    case buma3d::RESOURCE_FORMAT_R32_UINT:
    case buma3d::RESOURCE_FORMAT_R8G8_UINT:
    case buma3d::RESOURCE_FORMAT_R16G16_UINT:
    case buma3d::RESOURCE_FORMAT_R32G32_UINT:
    case buma3d::RESOURCE_FORMAT_R32G32B32_UINT:
    case buma3d::RESOURCE_FORMAT_R8G8B8A8_UINT:
    case buma3d::RESOURCE_FORMAT_R10G10B10A2_UINT:
    case buma3d::RESOURCE_FORMAT_R16G16B16A16_UINT:
    case buma3d::RESOURCE_FORMAT_R32G32B32A32_UINT:
    case buma3d::RESOURCE_FORMAT_D24_UNORM_S8_UINT:
    case buma3d::RESOURCE_FORMAT_D32_FLOAT_S8X24_UINT:
        return true;

    default:
        return false;
    }
}

bool IsSrgbFormat(RESOURCE_FORMAT _format)
{
    switch (_format)
    {
    case buma3d::RESOURCE_FORMAT_R8G8B8A8_UNORM_SRGB:
    case buma3d::RESOURCE_FORMAT_B8G8R8A8_UNORM_SRGB:
    case buma3d::RESOURCE_FORMAT_BC1_UNORM_SRGB:
    case buma3d::RESOURCE_FORMAT_BC2_UNORM_SRGB:
    case buma3d::RESOURCE_FORMAT_BC3_UNORM_SRGB:
    case buma3d::RESOURCE_FORMAT_BC7_UNORM_SRGB:
    case buma3d::RESOURCE_FORMAT_BC1_RGB_SRGB_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ETC2_R8G8B8_SRGB_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ETC2_R8G8B8A1_SRGB_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ETC2_R8G8B8A8_SRGB_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_4x4_SRGB_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_5x4_SRGB_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_5x5_SRGB_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_6x5_SRGB_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_6x6_SRGB_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_8x5_SRGB_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_8x6_SRGB_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_8x8_SRGB_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_10x5_SRGB_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_10x6_SRGB_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_10x8_SRGB_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_10x10_SRGB_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_12x10_SRGB_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_ASTC_12x12_SRGB_BLOCK_VK:
    case buma3d::RESOURCE_FORMAT_PVRTC1_2BPP_SRGB_BLOCK_IMG_VK:
    case buma3d::RESOURCE_FORMAT_PVRTC1_4BPP_SRGB_BLOCK_IMG_VK:
    case buma3d::RESOURCE_FORMAT_PVRTC2_2BPP_SRGB_BLOCK_IMG_VK:
    case buma3d::RESOURCE_FORMAT_PVRTC2_4BPP_SRGB_BLOCK_IMG_VK:
        return true;

    default:
        return false;
    }
}


}// namespace util
}// namespace buma3d
